# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
         echo 1.  what is in this directory?
         ls -a
         echo
         echo 2. Is Java Installed?
         java -version
         echo 3. Is git Installed?
         git --version
         echo 4 . What about build tools?
         mvn --version
         gradle --version
         ant -version
         echo 
         echo 5. where is the Android SDK Root?
         echo $ANDROID_SDK_ROOT
         echo
         echo 6. Where is the Selenium jars?
         echo $SELENIUM_JAR_PATH
         echo 
         echo 7. what is the workspace location
         echo $RUNNER_WORKSPACE
         echo
         echo 8 who is running this script?
         whoami
         echo 9 who is the disc laid out?
         df
         echo 10. what enviornment variables are available?
         env          
          
          
          
          
          
